import { Activity, Crown, Star, Users } from "lucide-react";

export const userStats = [
  {
    title: "Total Users",
    value: "3,420",
    change: "+12.5%",
    changeType: "positive" as const,
    icon: Users,
    description: "from last month",
  },
  {
    title: "Active Today",
    value: "1,234",
    change: "+8.2%",
    changeType: "positive" as const,
    icon: Activity,
    description: "users online now",
  },
  {
    title: "Premium Users",
    value: "892",
    change: "+23.1%",
    changeType: "positive" as const,
    icon: Crown,
    description: "subscription active",
  },
  {
    title: "Avg. Satisfaction",
    value: "4.8",
    change: "+0.3",
    changeType: "positive" as const,
    icon: Star,
    description: "out of 5.0",
  },
];

export const users = [
  {
    id: 1,
    name: "Alex Chen",
    email: "alex.chen@example.com",
    avatar: "/thoughtful-man.png",
    role: "Premium",
    status: "Active",
    joinDate: "2024-01-15",
    lastActive: "2 minutes ago",
    conversations: 234,
    satisfaction: 4.9,
    favoriteCharacter: "Luna AI",
    totalTokens: 45600,
    subscription: "Pro Plan",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    avatar: "/diverse-woman-portrait.png",
    role: "Admin",
    status: "Active",
    joinDate: "2023-11-20",
    lastActive: "5 minutes ago",
    conversations: 567,
    satisfaction: 4.8,
    favoriteCharacter: "Sage AI",
    totalTokens: 128900,
    subscription: "Enterprise",
  },
  {
    id: 3,
    name: "Maya Patel",
    email: "maya.patel@example.com",
    avatar: "/asian-woman-portrait.png",
    role: "Free",
    status: "Active",
    joinDate: "2024-02-10",
    lastActive: "1 hour ago",
    conversations: 89,
    satisfaction: 4.7,
    favoriteCharacter: "Echo AI",
    totalTokens: 12300,
    subscription: "Free Tier",
  },
  {
    id: 4,
    name: "David Kim",
    email: "david.kim@example.com",
    avatar: "/asian-man-portrait.png",
    role: "Premium",
    status: "Inactive",
    joinDate: "2023-12-05",
    lastActive: "2 days ago",
    conversations: 156,
    satisfaction: 4.6,
    favoriteCharacter: "Nova Bot",
    totalTokens: 34500,
    subscription: "Pro Plan",
  },
  {
    id: 5,
    name: "Emma Wilson",
    email: "emma.w@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Free",
    status: "Active",
    joinDate: "2024-03-01",
    lastActive: "30 minutes ago",
    conversations: 45,
    satisfaction: 4.5,
    favoriteCharacter: "Alex Bot",
    totalTokens: 8900,
    subscription: "Free Tier",
  },
  {
    id: 6,
    name: "James Rodriguez",
    email: "james.r@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Premium",
    status: "Active",
    joinDate: "2024-01-20",
    lastActive: "10 minutes ago",
    conversations: 178,
    satisfaction: 4.7,
    favoriteCharacter: "Aria AI",
    totalTokens: 28900,
    subscription: "Pro Plan",
  },
  {
    id: 7,
    name: "Lisa Zhang",
    email: "lisa.zhang@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Free",
    status: "Active",
    joinDate: "2024-02-15",
    lastActive: "45 minutes ago",
    conversations: 67,
    satisfaction: 4.4,
    favoriteCharacter: "Zara Bot",
    totalTokens: 9800,
    subscription: "Free Tier",
  },
  {
    id: 8,
    name: "Michael Brown",
    email: "michael.b@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Admin",
    status: "Active",
    joinDate: "2023-10-12",
    lastActive: "1 minute ago",
    conversations: 445,
    satisfaction: 4.9,
    favoriteCharacter: "Sage AI",
    totalTokens: 89600,
    subscription: "Enterprise",
  },
  {
    id: 9,
    name: "Sophie Martin",
    email: "sophie.m@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Premium",
    status: "Active",
    joinDate: "2024-01-08",
    lastActive: "20 minutes ago",
    conversations: 203,
    satisfaction: 4.8,
    favoriteCharacter: "Luna AI",
    totalTokens: 41200,
    subscription: "Pro Plan",
  },
  {
    id: 10,
    name: "Ryan Thompson",
    email: "ryan.t@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Free",
    status: "Inactive",
    joinDate: "2024-02-28",
    lastActive: "3 days ago",
    conversations: 23,
    satisfaction: 4.2,
    favoriteCharacter: "Echo AI",
    totalTokens: 3400,
    subscription: "Free Tier",
  },
  {
    id: 11,
    name: "Anna Kowalski",
    email: "anna.k@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Premium",
    status: "Active",
    joinDate: "2023-12-18",
    lastActive: "5 minutes ago",
    conversations: 312,
    satisfaction: 4.8,
    favoriteCharacter: "Nova Bot",
    totalTokens: 56700,
    subscription: "Pro Plan",
  },
  {
    id: 12,
    name: "Carlos Silva",
    email: "carlos.s@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Free",
    status: "Active",
    joinDate: "2024-03-05",
    lastActive: "2 hours ago",
    conversations: 78,
    satisfaction: 4.6,
    favoriteCharacter: "Aria AI",
    totalTokens: 11200,
    subscription: "Free Tier",
  },
  {
    id: 13,
    name: "Jennifer Lee",
    email: "jennifer.l@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Admin",
    status: "Active",
    joinDate: "2023-09-30",
    lastActive: "3 minutes ago",
    conversations: 523,
    satisfaction: 4.9,
    favoriteCharacter: "Sage AI",
    totalTokens: 102300,
    subscription: "Enterprise",
  },
  {
    id: 14,
    name: "Ahmed Hassan",
    email: "ahmed.h@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Premium",
    status: "Active",
    joinDate: "2024-01-25",
    lastActive: "15 minutes ago",
    conversations: 189,
    satisfaction: 4.7,
    favoriteCharacter: "Luna AI",
    totalTokens: 33800,
    subscription: "Pro Plan",
  },
  {
    id: 15,
    name: "Rachel Green",
    email: "rachel.g@example.com",
    avatar: "/placeholder.svg?height=40&width=40",
    role: "Free",
    status: "Active",
    joinDate: "2024-02-20",
    lastActive: "1 hour ago",
    conversations: 56,
    satisfaction: 4.3,
    favoriteCharacter: "Zara Bot",
    totalTokens: 7800,
    subscription: "Free Tier",
  },
];